site_name: Shift Software
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/Shift-Software/test
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust


